// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxelvmmlebvmhpgiybaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZWx2bW1sZWJ2bWhwZ2l5YmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDgyODgsImV4cCI6MjA2NzAyNDI4OH0.ovY9RuBwZrgecQjOcuDnJHyZfYZw7MRChb4746RU9SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});